# Generated by Django 4.2 on 2024-06-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_topic_alter_quesmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quiz.topic'),
            preserve_default=False,
        ),
    ]
