# Generated by Django 4.2 on 2024-06-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_quesmodel_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.URLField(),
        ),
    ]
