# Generated by Django 4.2 on 2024-06-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_alter_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='asdf'),
            preserve_default=False,
        ),
    ]
