# Generated by Django 4.2 on 2024-06-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_topic_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuesModel',
            new_name='Question',
        ),
    ]
