# Generated by Django 4.2 on 2024-06-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_rename_quesmodel_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
